version: '3'

services:
  app:
    build: .
    image: base-python:latest
    ports:
      - "8000:80"
    volumes:
      - "data:/data"
    environment:
      PHP_CONF_MEMORY_LIMIT: "-1"

volumes:
  data:
